[sheafy]
filters = ["scala"]
bundle_name = "bundle.md"
working_dir = "./hw/spinal/parallax"
use_gitignore = true

prologue = """
<!-- Start of Project Bundle -->
# Project Bundle

This is a bundle of all the source files in the project directory, including subdirectories.

"""

epilogue = """
<!-- End of Project Bundle -->
"""
